---
    - name: Install NGINX
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx' ]

# Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ nginx_http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ nginx_http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ nginx_http_conf }}"
        state: link
      notify: Reload Nginx

    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ nginx_http_port }}"
      ufw:
        rule: allow
        port: "{{ nginx_http_port }}"
        proto: tcp
